### PR TITLE
Better translation UI

### PR DESCRIPTION
**Pull request by fabn**
This pull request bring in #23 and #15 plus an addition to remove existing translations using javascript (see 3f67cfab5a21158f5242424d8b8c842f2ec95017).

With this the before_filter implemented in #14 is not needed anymore.

I've also relaxed globalize dependency to `~> 3.0.4` to allow usage with rails 3.2.x

If this gets merged #10, #19, #20, #28 and #29 may be closed since all of them will be addressed.

@stefanoverna, @dtengeri, @sepastian let me know if there is something else that should be done.

### CODE REVIEW

**Comment by dtengeri** [comment]
@fabn Nice job! I hope this can be merged.

**Comment by karlfreeman** [comment]
:+1: This is a lovely addition and worked perfectly on a new Rails 4.1 application I've just put together. :ship:.

**Comment by karlfreeman** [comment]
Heads up to anyone else trying to debug why 'destroying' a locale does not work in Rails 4. Make sure to put `:_destroy:` in your `permit_params`

``` ruby
permit_params translations_attributes: [:id, :locale, :your_localisable_attribute, :_destroy]
```

**Comment by fabn** [comment]
@karlfreeman if you're interested in this, I developed it further with some other additions. You can find it on my [fork](https://github.com/fabn/activeadmin-globalize).

There's also a demo of additional features for show action here: http://globalize.herokuapp.com/articles/3

**Comment by fabn** [comment]
@stefanoverna are you still interested in maintaining this gem? Otherwise I'll release my fork on rubygems.

Let me know

**Comment by besi** [comment]
+1 Nice work. I ran into an issue when trying this out with Rails 4 (Using my own fork based on your pull-request).

While `translation_status_flags` works, when I use `translated_row(:title)` I get an error:

```
undefined method `translated_row' for #<ActiveAdmin::Views::Pages::Show:0x007f9159bfd7d0>
```

**Comment by besi** [comment]
I don’t know why this pull request was closed. I just let you know that I use this branch in one of my project and I think it is a very good imrprovement to the existing solution.
Thanks=

**Comment by fabn** [comment]
@besi I just deleted the remote branch because I was doing some cleanup in my fork. If you're interested in it you can always find it [here](https://github.com/fabn/activeadmin-globalize). Feedback is very appreciated.

**Comment by besi** [comment]
Thanks a lot for letting me know. I did run into an issue but there was no issue tracker enabled on the repo:
- Create a new entity and only add the default translation (German in my case)
- I save
- The translation_status now shows German AND English even though I did not provide an English translation
- I edit the entity and save without changes
- Now only “German” is shown for translation_status which is correct.

The original plugin did that as well which I think is the reason for a problem that I am running into on production environment:
See https://github.com/globalize/globalize/issues/362

Let me know if you decide to enable the issue tracker then I will post issues there. Otherwise I will leave you my feedback here.

**Comment by fabn** [comment]
@besi I've just enabled the issue tracker on my fork, feel free to open issues there.

**Comment by besi** [comment]
@fabn Thanks, there we go: https://github.com/fabn/activeadmin-globalize/issues/1 (Proud to be No1)
